name: docs ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: dendron init, export and publish docs
        run: |
          yarn
          yarn dendron publish init
          yarn dendron publish export
          rm -fR docs/*
          mv .next/out/* docs/
      - name: Commit files
        run: |
          git config --local user.email "duchunmu@qq.com"
          git config --local user.name "ChunMu Du[bot]"
          git config --local pull.rebase true
          git config --local pull.ff only
          git checkout --no-guess docs
          git pull origin docs
          git add docs/
          git commit -m "publish"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: docs
